server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
